#question 1 :  Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:

A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import requests
import re
from selenium.webdriver.support.ui import WebDriverWait
import warnings
warnings.filterwarnings('ignore')

In [4]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')

# Getting the webpage of url 

url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)
# Creating empty list for storing data after scraping

Rank = []
Name = []
Artist = []
UploadDate = []
Views = []


# Scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
    
#scrapping name
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
    
    
#scrapping Artist
try:
    for i in driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[3]'):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")
    
    
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,' //table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]'):
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append('-')
# Scraping Views of videos


try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")

In [5]:
# Creating DataFrame from scraped data
wikipedia = pd.DataFrame({})
wikipedia['Rank']=Rank
wikipedia['Name']=Name
wikipedia['Artist']=Artist
wikipedia['Upload Date']=UploadDate
wikipedia['Views']=Views
wikipedia

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.00
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.05
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.57
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.89
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.88
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.74
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.08
7,8.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.79
8,9.,"""Wheels on the Bus""[25]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.77
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.76
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.64
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.18
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.80
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.70
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.70
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.67
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.53
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.46
20,21.,"""Dark Horse""[41]",Katy Perry,"February 20, 2014",3.42
21,22.,"""Waka Waka (This Time for Africa)""[42]",Shakira,"June 4, 2010",3.40
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.38
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.36
24,25.,"""Girls Like You""[45]",Maroon 5,"May 31, 2018",3.35
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.33
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.31
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.31
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.26
29,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,"June 14, 2018",3.24

# question 2 :  Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/. You need to find following details:

A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [8]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)

#clickin on International tab
International = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') # click button
International.click()

In [9]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]
#Scrapping Name
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
        Name.append(i.text.replace('-',""))
except NoSuchElementException:
    Name.append('-')
#Scrapping Series
try:
    
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
#scrapping Place
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
#Scrapping Time
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

In [10]:
# Create Dataframe

Fixtures=pd.DataFrame({})
Fixtures['Title']=Series
Fixtures['Name']=Name
Fixtures['Place']=Place
Fixtures['Date']=Date
Fixtures['Time']=Time
Fixtures

,Title,Name,Place,Date,Time
0,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,4th T20I,"Steyn City School Ground,",2 JAN 2023,5:15 PM
1,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,1st T20I,"Wankhede Stadium,",3 JAN 2023,7:00 PM
2,INDIA WOMEN U19 TOUR OF SOUTH AFRICA WOMEN U19,5th T20I,"Steyn City School Ground,",4 JAN 2023,1:30 PM
3,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,2nd T20I,"Maharashtra Cricket Association Stadium,",5 JAN 2023,7:00 PM
4,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,3rd T20I,"Saurashtra Cricket Association Stadium,",7 JAN 2023,7:00 PM
5,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,1st ODI,"Barsapara Cricket Stadium,",10 JAN 2023,1:30 PM
6,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,"Eden Gardens,",12 JAN 2023,1:30 PM
7,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,3rd ODI,"Greenfield International Stadium,",15 JAN 2023,1:30 PM

In [11]:
driver.close()

# question 3 : Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/ You need to find following details:

A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [42]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')

# get webpage
driver.get("https://www.guru99.com/")
driver.maximize_window()

In [44]:
# Click Selenium Button
Selenium = driver.find_element(By.XPATH,'//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') # click button
try:
    Selenium.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))
time.sleep(3)
# Click selenium exception handling  Button
exception_handling = driver.find_element(By.XPATH,"//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException:  #if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))
name=[]
desc=[]
#Scrapping Name
for i in driver.find_elements(By.XPATH,'//h2[@id="types-of-exceptions-in-selenium-webdriver"]/a/p/strong'):
    name.append(i.text)
for i in driver.find_elements(By.XPATH,'//h2[@id="types-of-exceptions-in-selenium-webdriver"]/a/p'):
    desc.append(i.text)

    
Selenium_Exception=pd.DataFrame()
Selenium_Exception['Exception name']=name
Selenium_Exception['Description']=desc
Selenium_Exception

Empty DataFrame
Columns: [Exception name, Description]
Index: []

# question 4 : Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/ You have to find following details:

A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [16]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')
driver.maximize_window()
driver.get('https://www.statisticstimes.com')
time.sleep(3)

In [17]:
driver.find_element(By.XPATH,'/html/body/div[1]/div/a').click()

In [19]:
 #Clicking on Economy button
driver.find_element(By.XPATH,"//div[@class='navbar']/div[2]/button").click()
#Clicking on India
driver.find_element(By.XPATH,"//div[@class='dropdown-content']/a[3]").click()

In [20]:
# Clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(3)

In [21]:
# Creating empty list
Rank = []
State = []
GSDP2 = []
Share = []
GDPbillion = []
# Scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
# Scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
# Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
# Scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
# Scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDPbillion.append(i.text)
except NoSuchElementException:
    GDPbillion.append("_")

In [22]:
INDIA=pd.DataFrame()
INDIA['RANK']=Rank
INDIA['STATE']=State
INDIA['GSDP2']=GSDP2
INDIA['SHARE']=Share
INDIA['GDPbillion']=GDPbillion
INDIA

   RANK                      STATE      GSDP2   SHARE GDPbillion
0     1                Maharashtra  2,632,792  13.94%    399.921
1     2                 Tamil Nadu  1,630,208   8.63%    247.629
2     3              Uttar Pradesh  1,584,764   8.39%    240.726
3     4                    Gujarat  1,502,899   7.96%    228.290
4     5                  Karnataka  1,493,127   7.91%    226.806
..  ...                        ...        ...     ...        ...
61   29                     Sikkim     25,141   0.15%     17,060
62   30                   Nagaland     24,534   0.15%          -
63   31          Arunachal Pradesh     22,488   0.13%          -
64   32                    Mizoram     20,947   0.13%     17,797
65   33  Andaman & Nicobar Islands          -       -          -

[66 rows x 5 columns]

In [23]:
driver.close()

# question 5 : Scrape the details of trending repositories on Github.com.
Url = https://github.com/ You have to find the following details:

A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [25]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')
url=('https://github.com/')
driver.get(url)

In [46]:
# Click on explore

explore = driver.find_element(By.XPATH,'//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver.get(explore.get_attribute('href'))

In [30]:
# Click on Trending

trending = driver.find_element(By.XPATH,'//*[@href="/trending"]')
try:
    driver.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

In [28]:
#Creating empty list:
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))
    
    
# Scraping Repository Title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(2)
    
        # Scraping Repository Description data
    try:
        desc = driver.find_element(By.XPATH,"//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # Scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
     # Scraping Languages used data
    lang=[]
    try:
        for i in driver.find_elements(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]'):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        lang.append('-')

In [29]:
print(len(repository_title),len(Description),len(Contributors),len(Language))

25 25 25 25

In [31]:
Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,LAION-AI / Open-Assistant,OpenAssistant is a chat-based assistant that u...,35,"[Jupyter Notebook, Python, TypeScript, JavaScr..."
1,karpathy / nanoGPT,"The simplest, fastest repository for training/...",2,[Python]
2,sczhou / CodeFormer,[NeurIPS 2022] Towards Robust Blind Face Resto...,3,"[Python, Cuda, C++]"
3,DarkFlippers / unleashed-firmware,Flipper Zero Unleashed Firmware,191,"[C, Python, HTML, PHP, C++, Assembly]"
4,ytdl-org / youtube-dl,Command-line program to download videos from Y...,777,"[Python, Other]"
5,google / osv-scanner,Vulnerability scanner written in Go which uses...,15,"[Go, Other]"
6,pola-rs / polars,"Fast multi-threaded, hybrid-streaming DataFram...",141,"[Rust, Python, Other]"
7,neonbjb / tortoise-tts,A multi-voice TTS system trained with an empha...,11,"[Python, HTML, Jupyter Notebook]"
8,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,75,[]
9,dair-ai / Prompt-Engineering-Guide,🐙 Guide and resources for prompt engineering,3,[]
10,Ebazhanov / linkedin-skill-assessments-quizzes,Full reference of LinkedIn answers 2022 for sk...,"1,269",[Python]
11,ocornut / imgui,Dear ImGui: Bloat-free Graphical User interfac...,313,"[C++, C, Objective-C++, Objective-C, GLSL, GDB]"
12,AmruthPillai / Reactive-Resume,A one-of-a-kind resume builder that keeps your...,84,"[TypeScript, SCSS, JavaScript, Dockerfile, Kot..."
13,PRQL / prql,PRQL is a modern language for transforming dat...,35,"[Rust, CSS, JavaScript, HTML, Java, Shell, Other]"
14,A-poc / RedTeam-Tools,Tools and Techniques for Red Team / Penetratio...,-,[]
15,jerryjliu / gpt_index,An index created by GPT to organize external i...,6,"[Python, Jupyter Notebook]"
16,imDazui / Tvlist-awesome-m3u-m3u8,直播源相关资源汇总 📺 💯 IPTV、M3U —— 勤洗手、戴口罩，祝愿所有人百毒不侵,-,[]
17,aurae-runtime / aurae,Distributed systems runtime daemon written in ...,25,"[Rust, Nix, Shell, TypeScript, Makefile, Rende..."
18,zlib-searcher / zlib-searcher,search zlib/libgen index to get ipfs_cid.,9,"[TypeScript, Rust, Shell, Python, Makefile, Do..."
19,BrunoLevy / learn-fpga,"Learning FPGA, yosys, nextpnr, and RISC-V",11,"[C++, Verilog, GLSL, C, Assembly, Makefile, Ot..."
20,alist-org / alist,🗂️A file list program that supports multiple s...,30,"[Go, Other]"
21,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,626","[TypeScript, JavaScript, CSS, Shell, Dockerfil..."
22,Atlas-OS / Atlas,"🚀 An open-source modification of Windows 10, d...",18,"[Batchfile, PowerShell]"
23,SheerSt / pokewilds,PokeWilds - A Gen 2 Game/Engine using libGDX,8,[Assembly]
24,jwasham / coding-interview-university,A complete computer science study plan to beco...,282,[]

# question 6 : Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/ You have to find the following details:

A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [67]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')
driver.maximize_window()
# Getting the webpage of mentioned url 
driver.get('https://www.billboard.com/')

In [72]:
#Clicking on hot100
chart=driver.find_element(By.XPATH,'/html/body/div[3]/div[8]/div/div/div/ul/li[1]/h3/a').click()

hot100=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a').click()
# Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []
# Scraping name
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]'):
    Song_Name.append(i.text)
len(Song_Name)

100

In [73]:
#Scrappin Artist name 1 st one
Artist_Name.append(driver.find_element(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)

#Remainig Artist Name
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
Artist_Name.extend([i.text for i in artistTag])

#Scapping Rank
rank=[]
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])

#Remaining RAnk
Rank=[]
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

In [74]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [76]:
# slicing as per requirement
lastweekpos=Rank[0::3]
lastweekpos.insert(0,rank[0])
peakPos=Rank[1::3]
peakPos.insert(0,rank[1])
weeksonBoard=Rank[2::3]
weeksonBoard.insert(0,rank[2])

#check length of all
len(Song_Name),len(Artist_Name),len(lastweekpos),len(peakPos),len(weeksonBoard)

(100, 100, 133, 133, 133)

In [77]:
# Create Dataframe
df=pd.DataFrame()
df['SongName']=Song_Name[0:100]
df['ArtistName']=Artist_Name
df['Last Week']=lastweekpos[0:100]
df["PeekPosition"]=peakPos[0:100]
df['Weeks On board']=weeksonBoard[0:100]
df

,SongName,ArtistName,Last Week,PeekPosition,Weeks On board
0,All I Want For Christmas Is You\nMariah Carey\...,Mariah Carey,1,1,57
1,Rockin' Around The Christmas Tree\nBrenda Lee\...,Brenda Lee,2,2,51
2,Jingle Bell Rock\nBobby Helms\n4\n3\n48,Bobby Helms,4,3,48
3,A Holly Jolly Christmas\nBurl Ives\n5\n4\n31,Burl Ives,5,4,31
4,Last Christmas\nWham!\n6\n5\n30,Wham!,6,5,30
...,...,...,...,...,...
95,Down Home\nJimmie Allen\n-\n88\n5,Jimmie Allen,43,43,2
96,One Thing At A Time\nMorgan Wallen\n81\n37\n3,Morgan Wallen,,,
97,Hold Me Closer\nElton John & Britney Spears\n8...,Elton John & Britney Spears,83,74,16
98,Far\nSZA\n61\n61\n2,SZA,,,
99,All Mine\nBrent Faiyaz\n95\n42\n20,Brent Faiyaz,68,22,3

# question 7 : Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/hr-recruiters-consultants You have to find the following details:

A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [7]:
driver=webdriver.Chrome(r'C:\Users\Rishabh Singh\Downloads\chromedriver_win32\chromedriver.exe')

driver.maximize_window()
# Getting the webpage of mentioned url 
url=('https://www.naukri.com/hr-recruiters-consultants')
driver.get(url)
time.sleep(2)

In [8]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'/html/body/div[1]/div/ul/li[2]/a')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)
# Fetching search button, sending keys and clicking on it
search = driver.find_element(By.XPATH,"//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()     
time.sleep(3)

In [9]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)

#Scraping data of Designation
for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    
#Scraping data of company name
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [10]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Company Recruiter
11,Mubarak,Company HR,MoneyTap,Ahmedabad
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,subhas patel
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Founder CEO
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,UK - (london)
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,Indore
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,InstaFinancials
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Human Resource
29,kumar,Proprietor,trainin,Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,Kalpana Dumpala
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Executive Hiring
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Hyderabad / Secunderabad
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mubarak
34,Avodha,Business Development Associate,Nikitha Palaparthi,Company HR
35,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore
36,Amit Sharma,Consultant,ASCO consulting,Kushal Rastogi
37,Kanan,senior technology instructor,NY INST,Company HR
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Mumbai
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,Mahesh Babu Channa
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,HR Team Lead
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Hyderabad / Secunderabad
42,Ankit Sinha,Head Analytics,Suntech Global,Vaishnavi Kudalkar
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,HR Executive
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Mumbai
45,Ashwini,Director Global Delivery,MRP Advisers,Priyanka Akiri
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,HR Manager
47,Rajani Nagaraj,HR Manager,WildJasmine,Hyderabad
48,ROHIT Kumar,Architect,LNT Private Limited,Kapil Devang
49,Amir Chowdhury,Managing Partner,Granular.ai,HR Manager

# question 8: Scrape the details of Highest selling novels.
URL = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare You have to find the following details:

A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [17]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

# get webpage
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [20]:
#Creating empty list
Bookname = []
Authorname = []
Volumessold = []
Publisher = []
Genre = []
#scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr/td[2]"):
    Bookname.append(i.text)
    
#Scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Authorname.append(i.text)
    except NoSuchElementException:
        Authorname.append('-')
time.sleep(1)

#Scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[4]"):
    Volumessold.append(i.text)
    
#Scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[5]"):
    Publisher.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[6]"):
    Genre.append(i.text)

In [19]:
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Bookname
Novels['Author'] = Authorname
Novels['Volume sold'] = Volumessold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [21]:
driver.close()

# question 9: Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:

A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [22]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")
# get webpage
driver.get("https://www.imdb.com/list/ls095964455/")
driver.maximize_window()

In [23]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
#Scraping data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
#Scraping data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
#Scraping data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
#Scraping data of votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [24]:
# Creating dataframe for scraped data
TVseries=pd.DataFrame({})
TVseries['Name'] = Name
TVseries['Year Span'] = Year_span
TVseries['Genre'] = Genre
TVseries['Run Time'] = Run_time
TVseries['Ratings'] = Ratings
TVseries['Votes'] = Votes
TVseries

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,100,227"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,190,494"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"994,228"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"294,241"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"253,344"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,377"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,987"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"199,951"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,715"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"247,005"

In [25]:
driver.close()

# question 10 :  Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You have to find the following details:

A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [37]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")
# get webpage
driver.get(" https://archive.ics.uci.edu/")
driver.maximize_window()

In [38]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)

# Fetching page urls of all datasets 
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)

# Fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [39]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

In [40]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    
    
    #Scraping data type
    try:
        data_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    
    
    #scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    
    
    # Scraping Attribute type
    try:
        attribute_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    
    # Scraping No of instances
    try:
        instances = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    
    
    # Scraping year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')

In [41]:
# Creating dataframe 

ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name[:622]
ML['Data Type'] = Data_type[:622]
ML['Task'] = Task[:622]
ML['Attribute type'] = Attribute_type[:622]
ML['No of instance'] = No_of_instances[:622]
ML['No of attributes'] = No_of_attributes[:622]
ML['Year'] = Year[:622]
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990

In [79]:
driver.close()